/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks/$deckId'
import { Route as DecksDeckIdPresenterRouteImport } from './routes/decks/$deckId.presenter'
import { Route as DecksDeckIdSlideSlideIdRouteImport } from './routes/decks/$deckId.slide.$slideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdPresenterRoute = DecksDeckIdPresenterRouteImport.update({
  id: '/presenter',
  path: '/presenter',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdSlideSlideIdRoute = DecksDeckIdSlideSlideIdRouteImport.update({
  id: '/slide/$slideId',
  path: '/slide/$slideId',
  getParentRoute: () => DecksDeckIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/decks/$deckId/presenter': typeof DecksDeckIdPresenterRoute
  '/decks/$deckId/slide/$slideId': typeof DecksDeckIdSlideSlideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/decks/$deckId/presenter': typeof DecksDeckIdPresenterRoute
  '/decks/$deckId/slide/$slideId': typeof DecksDeckIdSlideSlideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/decks/$deckId/presenter': typeof DecksDeckIdPresenterRoute
  '/decks/$deckId/slide/$slideId': typeof DecksDeckIdSlideSlideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks/$deckId'
    | '/decks/$deckId/presenter'
    | '/decks/$deckId/slide/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decks/$deckId'
    | '/decks/$deckId/presenter'
    | '/decks/$deckId/slide/$slideId'
  id:
    | '__root__'
    | '/'
    | '/decks/$deckId'
    | '/decks/$deckId/presenter'
    | '/decks/$deckId/slide/$slideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksDeckIdRoute: typeof DecksDeckIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/presenter': {
      id: '/decks/$deckId/presenter'
      path: '/presenter'
      fullPath: '/decks/$deckId/presenter'
      preLoaderRoute: typeof DecksDeckIdPresenterRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/slide/$slideId': {
      id: '/decks/$deckId/slide/$slideId'
      path: '/slide/$slideId'
      fullPath: '/decks/$deckId/slide/$slideId'
      preLoaderRoute: typeof DecksDeckIdSlideSlideIdRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
  }
}

interface DecksDeckIdRouteChildren {
  DecksDeckIdPresenterRoute: typeof DecksDeckIdPresenterRoute
  DecksDeckIdSlideSlideIdRoute: typeof DecksDeckIdSlideSlideIdRoute
}

const DecksDeckIdRouteChildren: DecksDeckIdRouteChildren = {
  DecksDeckIdPresenterRoute: DecksDeckIdPresenterRoute,
  DecksDeckIdSlideSlideIdRoute: DecksDeckIdSlideSlideIdRoute,
}

const DecksDeckIdRouteWithChildren = DecksDeckIdRoute._addFileChildren(
  DecksDeckIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksDeckIdRoute: DecksDeckIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
